name: flutter_Weather_app_harsh
description: Polished weather app â€” bold & vibrant visuals for hackathon submission.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  lottie: ^2.7.0
  intl: ^0.19.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/clear.json
    - assets/lottie/clouds.json
    - assets/lottie/rain.json
    - assets/lottie/thunder.json
    - assets/lottie/snow.json
    - assets/lottie/mist.json
